version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL="postgresql://postgres:postgres@db:5432/shopper?schema=backend"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
